REM EXAMPLE CODE OF RUKA BASIC
REM (C) 2025 KAJIZUKA TAICHI. ALL RIGHTS RESERVED

CALL FACTORIAL(5)
EXIT PROGRAM

REM CALCULATE FACTORIAL OF THE NUMBER
SUB FACTORIAL(NUMBER)
    REM INITIALIZE VARIABLES
    LET COUNT = 2
    LET RESULT = 1

    REM LOOP TO CALCULATE FACTORIAL
    WHILE TRUE
        REM CHECK IF IT COMES TO END OF LOOP
        IF COUNT > NUMBER
            REM BREAK FROM LOOP
            EXIT WHILE
        END IF

        REM MULTIPLY RESULT BY COUNT
        LET RESULT = RESULT * COUNT

        REM INCREMENT COUNTER
        LET COUNT = COUNT + 1
    END WHILE

    REM RESET COUNTER
    LET COUNT = 0
END SUB
